# Usa una base image di Nginx
FROM nginx:alpine

# Copia i tuoi file nella directory appropriata di Nginx
COPY ./static /usr/share/nginx/html/static
COPY ./templates /usr/share/nginx/html/templates
COPY ./config/nginx.conf /etc/nginx/nginx.conf

# Espone la porta 6001
EXPOSE 6001


CMD ["nginx", "-g", "daemon off;"]