version: "3.8"
services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "5001:5001"
    networks:
      - app-network

  backend:
    build:
      context: ./backend
    ports:
      - "5000:5000"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
