version: "3.8"

services:

  # Servizio del database
  database:
    image: postgres:latest
    container_name: cat_database
    environment:
      - POSTGRES_USER=antoniotrid
      - POSTGRES_PASSWORD=napibrfan
      - POSTGRES_DB=cat_database
    volumes:
      - cat_database_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5002:5432"
    networks:
      - app-network

  # Servizio del frontend
  frontend:
    build:
      context: ./frontend
    networks:
      - app-network

  # Servizio del backend
  backend:
    build:
      context: ./backend
    ports:
      - "5000:5000"
    networks:
      - app-network
    depends_on:
      - database

  # Reverse proxy Nginx
  reverse_proxy:
    image: nginx
    container_name: reverse_proxy
    volumes:
      - ./frontend/config/nginx.conf:/etc/nginx/nginx.conf  # Monta il file nginx.conf principale
      - ./frontend:/usr/share/nginx/html  # I file statici del frontend
    ports:
      - "5003:5003"  # Espone la porta 5003 del reverse proxy
    depends_on:
      - frontend
      - backend
    networks:
      - app-network


networks:
  app-network:
    driver: bridge

volumes:
  cat_database_data:
    driver: local
