FASCICOLO_1 = [1, "Primo fascicolo", "Questo è il contenuto del primo fascicolo", False]
FASCICOLO_2 = [2, "Secondo fascicolo", "Questo è il contenuto del secondo fascicolo", True]
FASCICOLO_3 = [3, "Terzo fascicolo", "Questo è il contenuto del terzo fascicolo", True]
FASCICOLO_4 = [4, "Quarto fascicolo", "Questo è il contenuto del quarto fascicolo", False]
FASCICOLO_5 = [5, "Quinto fascicolo", "Questo è il contenuto del quinto fascicolo", False]
FASCICOLO_6 = [6, "Sesto fascicolo", "Questo è il contenuto del sesto fascicolo", True]
FASCICOLO_7 = [7, "Settimo fascicolo", "Questo è il contenuto del settimo fascicolo", False]
FASCICOLO_8 = [8, "Ottavo fascicolo", "Questo è il contenuto del ottavo fascicolo", True]